@extends('layouts.app')

@section('content')
<div class="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-[#8b7355]">Super admin</p><h1 class="mt-2 font-display text-4xl font-bold tracking-tight">Kelola user admin</h1><p class="mt-3 text-sm text-[#765c47]">Buat akses satuan atau upload banyak user dengan template yang tersedia.</p></div><a href="{{ route('admin.index') }}" class="text-sm font-bold text-[#8b5e00]">← Kembali ke workspace</a></div>
<div class="mb-6 grid gap-4 lg:grid-cols-2">
    <div class="rounded-2xl border border-[#eadfca] bg-[#fffdf4] p-6"><p class="text-xs font-bold uppercase tracking-[0.16em] text-[#8b7355]">01 · Format data</p><h2 class="mt-2 font-display text-2xl font-bold">Download template Excel</h2><p class="mt-3 text-sm leading-6 text-[#765c47]">Gunakan format resmi agar data user terbaca dengan benar. Kolom role hanya menerima <span class="font-mono text-[#8b5e00]">admin</span> atau <span class="font-mono text-[#8b5e00]">super_admin</span>.</p><a href="{{ route('admin.users.template') }}" class="mt-5 inline-flex rounded-xl bg-[#fff200] px-5 py-3 text-sm font-bold text-[#543019] shadow-[3px_3px_0_#543019]">Download template ↓</a></div>
    <form action="{{ route('admin.users.import') }}" method="POST" enctype="multipart/form-data" class="rounded-2xl bg-[#543019] p-6 text-white">@csrf<p class="text-xs font-bold uppercase tracking-[0.16em] text-[#fff200]">02 · Bulk access</p><h2 class="mt-2 font-display text-2xl font-bold">Upload user dari Excel</h2><p class="mt-3 text-sm leading-6 text-[#f8e9c2]">Password minimal 8 karakter. Email yang sudah terdaftar atau baris tidak valid akan dilewati.</p><label class="mt-5 flex cursor-pointer items-center justify-between rounded-xl border border-dashed border-[#8b5e00] bg-[#6b4025] px-4 py-4 transition hover:border-[#fff200]"><span id="users-file-name" class="truncate text-sm font-bold">Pilih file Excel</span><span class="text-xs font-bold text-[#fff200]">XLSX / CSV</span><input type="file" name="file" accept=".xlsx,.xls,.csv" class="sr-only" required onchange="document.getElementById('users-file-name').textContent = this.files[0]?.name || 'Pilih file Excel'"></label><button class="mt-4 rounded-xl bg-[#fff200] px-5 py-3 text-sm font-bold text-[#543019]">Import user →</button></form>
</div>
@if (session('import_errors'))
    <div class="mb-6 rounded-2xl border border-[#ead1a2] bg-[#fff7e5] p-5 text-sm text-[#76551c]"><p class="font-bold">Baris yang dilewati</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach (session('import_errors') as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif
<div class="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]">
    <form action="{{ route('admin.users.store') }}" method="POST" class="rounded-2xl border border-[#eadfca] bg-[#fffdf4] p-6">@csrf<p class="text-xs font-bold uppercase tracking-[0.16em] text-[#8b7355]">Tambah user</p><div class="mt-5 space-y-4"><label class="block"><span class="text-sm font-bold">Nama</span><input name="name" value="{{ old('name') }}" required class="mt-2 w-full rounded-xl border border-[#ead9b8] bg-white px-4 py-3 text-sm outline-none focus:border-[#ffc20e]"></label><label class="block"><span class="text-sm font-bold">Email</span><input type="email" name="email" value="{{ old('email') }}" required class="mt-2 w-full rounded-xl border border-[#ead9b8] bg-white px-4 py-3 text-sm outline-none focus:border-[#ffc20e]"></label><label class="block"><span class="text-sm font-bold">Role</span><select name="role" class="mt-2 w-full rounded-xl border border-[#ead9b8] bg-white px-4 py-3 text-sm outline-none focus:border-[#ffc20e]"><option value="admin">Admin biasa</option><option value="super_admin">Super admin</option></select></label><label class="block"><span class="text-sm font-bold">Password</span><input type="password" name="password" required class="mt-2 w-full rounded-xl border border-[#ead9b8] bg-white px-4 py-3 text-sm outline-none focus:border-[#ffc20e]"></label><label class="block"><span class="text-sm font-bold">Konfirmasi password</span><input type="password" name="password_confirmation" required class="mt-2 w-full rounded-xl border border-[#ead9b8] bg-white px-4 py-3 text-sm outline-none focus:border-[#ffc20e]"></label></div><button class="mt-5 rounded-xl bg-[#543019] px-5 py-3 text-sm font-bold text-white">Tambah user →</button></form>
    <div class="rounded-2xl border border-[#eadfca] bg-[#fffdf4] p-6"><p class="text-xs font-bold uppercase tracking-[0.16em] text-[#8b7355]">User terdaftar</p><div class="mt-5 divide-y divide-[#eadfca]">@foreach ($users as $user)<div class="flex items-center justify-between gap-4 py-4"><div><p class="font-bold">{{ $user->name }}</p><p class="mt-1 text-xs text-[#765c47]">{{ $user->email }}</p></div><span class="rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-wider {{ $user->isSuperAdmin() ? 'bg-[#fff200] text-[#543019]' : 'bg-[#fff8d6] text-[#8b5e00]' }}">{{ $user->isSuperAdmin() ? 'Super admin' : 'Admin' }}</span></div>@endforeach</div></div>
</div>
@endsection
